feature: src tag
mennanov/fieldmask-utils pull request #38
Opened 2023-08-17 16:24 UTC by zhuliquan

some times, `mask` may using json field. this feature we can copy according to field's tag of src object.
useage：
```go
type A struct {
	Field1 string
	Field2 int `db:"some_field"`
}
type B struct {
	Field1 string `struct:"a_name"`
	A      A      `db:"another_name"`
}
src := &B{
	Field1: "B Field1",
	A: A{
		Field1: "A Field 1",
		Field2: 1,
	},
}
mask, _ = fieldmask_utils.MaskFromPaths([]string{"Field1","another_name.some_field"}, func(s string) string {return s})
dst := make(map[string]interface{})
err = fieldmask_utils.StructToMap(mask, src, dst, fieldmask_utils.WithSrcTag("db"))
fmt.Println(err)
// dst is map[string]interface{}{
// 	"Field1": src.Field1,
// 	"another_name": map[string]interface{}{
// 		"some_field": src.A.Field2,
// 	},
// }
fmt.Println(dst)
```

2023-08-18 05:27 UTC, mennanov requested changes
Good job! I left a few comments to address for you.
Thanks!

2023-08-18 05:27 UTC, mennanov commented on copy.go
> +			srcName := dstKey(userOptions.SrcTag, srcType.Field(i))
Please, rename the `dstKey` function to `fieldName` as it is no longer dst specific

2023-08-18 05:27 UTC, mennanov commented on copy.go
> +	SrcTag string // copy according to src tag, i.g. json
Please, move this comment 1 line above.
Also add a comment for the `DstTag` field

2023-08-18 05:27 UTC, mennanov commented on copy.go
> +// WithSrcTag set SrcTag of option, you can copy field according to field's tag of src object.
```suggestion
// WithSrcTag sets an option that gets the source field name from the field's tag.
```

2023-08-18 05:27 UTC, mennanov commented on copy_test.go
> +
Create a separate test function for this test case

2023-08-18 05:27 UTC, mennanov commented on copy_test.go
> +	}, dst)
Create a separate test function for this test case

2023-08-18 15:19 UTC, zhuliquan commented
Thanks for reviewing,  I have modified the code according to your suggestions.

2023-08-19 15:42 UTC, mennanov approved these changes

2023-08-19 15:45 UTC, merged

2023-08-19 15:45 UTC, mennanov commented
Thanks!