Tutorial on how to convert a protobuf message and filter certain fields to a resulting map.
mennanov/fieldmask-utils pull request #42
Opened 2024-01-31 03:12 UTC by marcoshuck

This PR addressed the discussion raised in #41 

I ended up copying the `CamelCase` code from the function to my personal open source project to avoid code duplications due to the limitation of the github protobuf project being deprecated, we can remove the reference if it doesn't make sense to keep it in here.

2024-01-31 03:29 UTC, marcoshuck commented
Seems CI pipelines are failing, looking into it.

2024-02-01 17:31 UTC, mennanov requested changes

2024-02-01 17:31 UTC, mennanov commented on README.md
Hm... i don't think that bringing a new dependency is justified in this case.
The purpose of this callback function is to provide a mapping from the proto field names to the golang struct field names. They may not even match (e.g. "a" can be mapped to "b").

I would just add more details to the `README.md` file: extend the existing examples with a real callback function to make it clear how it is supposed to be used.

I hope this makes sense.
Thanks!

2024-02-01 17:32 UTC, mennanov commented
> Seems CI pipelines are failing, looking into it.

Yeah, i think i need to upgrade the dependencies and go version. I'll do that in a separate PR.

2024-02-02 15:49 UTC, marcoshuck commented on README.md
It does, I'll remove the Go code and improve the README

2024-02-04 15:10 UTC, mennanov commented
> > Seems CI pipelines are failing, looking into it.
> 
> Yeah, i think i need to upgrade the dependencies and the go version. I'll do that in a separate PR.

I ended up not upgrading the go version in `go.mod` since it may impact the existing users of the library as according to the docs (https://go.dev/doc/modules/gomod-ref#go):

> Go toolchains refuse to use modules declaring newer Go versions.

I updated Github Actions tests for go 1.21 though.

2024-02-12 16:38 UTC, marcoshuck commented on README.md
I've removed the dependency 😄

2024-02-13 01:56 UTC, mennanov reviewed
Looks good overall, but please revert the `go.sum` changes

2024-02-13 01:56 UTC, mennanov commented on go.sum
lease revert the changes in this file.

2024-02-13 02:04 UTC, marcoshuck commented on go.sum
Interesting, seems I forgot to run `go mod tidy`. Done!

2024-02-15 06:33 UTC, mennanov approved these changes
Looks good!

2024-02-15 06:34 UTC, merged

2024-02-15 06:34 UTC, mennanov commented
Thanks for contributing!